import { Language } from './types';

export const API_BASE_URL = '/api';

export const TRANSLATIONS = {
  [Language.EN]: {
    home: "Home",
    about: "About / News",
    contact: "Contact Me",
    pokemon: "Pokemon Cards",
    baseball: "Baseball",
    football: "Football",
    viewAll: "View All Cards",
    buy: "Buy",
    close: "Close",
    info: "Info (Price Chart)",
    condition: "Condition",
    set: "Set",
    year: "Year",
    price: "Price",
    loading: "Loading cards...",
    error: "Something went wrong.",
    scanQr: "Scan to Buy on LINE",
    contactTitle: "Get in Touch",
    submit: "Send Message",
    newsTitle: "Latest News",
  },
  [Language.TH]: {
    home: "หน้าหลัก",
    about: "เกี่ยวกับเรา / ข่าวสาร",
    contact: "ติดต่อเรา",
    pokemon: "การ์ดโปเกมอน",
    baseball: "เบสบอล",
    football: "ฟุตบอล",
    viewAll: "ดูการ์ดทั้งหมด",
    buy: "ซื้อ",
    close: "ปิด",
    info: "ข้อมูล (กราฟราคา)",
    condition: "สภาพ",
    set: "ชุด",
    year: "ปี",
    price: "ราคา",
    loading: "กำลังโหลด...",
    error: "เกิดข้อผิดพลาด",
    scanQr: "สแกนเพื่อซื้อผ่าน LINE",
    contactTitle: "ติดต่อเรา",
    submit: "ส่งข้อความ",
    newsTitle: "ข่าวสารล่าสุด",
  },
  [Language.JP]: {
    home: "ホーム",
    about: "ニュース",
    contact: "お問い合わせ",
    pokemon: "ポケモンカード",
    baseball: "野球",
    football: "サッカー",
    viewAll: "すべてのカード",
    buy: "購入",
    close: "閉じる",
    info: "価格推移",
    condition: "状態",
    set: "セット",
    year: "年",
    price: "価格",
    loading: "読み込み中...",
    error: "エラーが発生しました",
    scanQr: "LINEで購入",
    contactTitle: "お問い合わせ",
    submit: "送信",
    newsTitle: "最新ニュース",
  }
};